### ISSUE TITLE
git镜像地址的问题

### ISSUE THREAD

**Issue by kuangxiaoye** [8Mi-Tech/8Mi-ClashController#1]
作者大大您好 非常感谢您的代码

由于租赁的gpu服务器不能翻墙 哈哈哈  这让我在配置里的https://github.com无响应

请问还有其他解决方式吗 

感谢

**Comment by 8MiYile** [comment]
额 其实可以更换源github来源的 但是我没写明白。。。

**Comment by 8MiYile** [comment]
https://github.com/8Mi-Tech/8Mi-ClashLCI/commit/aea4314de7efe0af4c5794ff2b25fc2b15fac3a5
